export const TEAM_DIRECTORY_REQUEST = "TEAM_DIRECTORY_REQUEST";
export const TEAM_DIRECTORY_SUCCESS = "TEAM_DIRECTORY_SUCCESS";
export const TEAM_DIRECTORY_FAIL = "TEAM_DIRECTORY_FAIL";
export const TEAM_DIRECTORY_RESET = "TEAM_DIRECTORY_RESET";

export const SEARCH_QUERY = "SEARCH_QUERY";
export const SEARCH_QUERY_RESET = "SEARCH_QUERY_RESET";
